from amber_lib.models.bases import Model, Property
from amber_lib.models.primaries import Assemblage
from amber_lib.models import components


class Product(Model):
    id = Property(int)
    assemblage = Property(Assemblage)
    arm = Property(components.Arm)
    audit = Property(components.Audit)
    bulb = Property(components.Bulb)
    category = Property(components.Category)
    collection = Property(components.Collection)
    construction_information = Property(components.ConstructionInformation)
    cushions = Property(components.Cushions)
    description = Property(components.Description)
    doors = Property(components.Doors)
    drawers = Property(components.Drawers)
    durability = Property(components.Durability)
    electrical = Property(components.Electrical)
    fiber = Property(components.Fiber)
    flame = Property(components.Flame)
    footboard = Property(components.Footboard)
    footrest = Property(components.Footrest)
    frame = Property(components.Frame)
    glass = Property(components.Glass)
    headboard = Property(components.Headboard)
    identity = Property(components.Identity)
    images = Property(components.Images)
    interior_dimension = Property(components.InteriorDimension)
    instructions = Property(components.Instructions)
    leather = Property(components.Leather)
    manufacturer = Property(components.Manufacturer)
    option_sets = Property(components.OptionSets)
    ordering_information = Property(components.OrderingInformation)
    pattern = Property(components.Pattern)
    pricing = Property(components.Pricing)
    pedestal = Property(components.Pedestal)
    pillows = Property(components.Pillows)
    promotional_tags = Property(components.PromotionalTags)
    overall_dimensions = Property(components.OverallDimensions)
    seat = Property(components.Seat)
    shade = Property(components.Shade)
    shelves = Property(components.Shelves)
    shipping_information = Property(components.ShippingInformation)
    suspension_point = Property(components.SuspensionPoint)
    table_leaves = Property(components.TableLeaves)
    textile = Property(components.Textile)
    visibility = Property(components.Visibility)
    weight = Property(components.Weight)
